"""
app/services/hermes_host_jobs.py

Task 3.14 -- one-click native Hermes setup via a host helper.

The backend runs in a container and cannot execute anything on the Windows
host. This service is the gateway half of the workaround: a tiny helper
(installed once on the host via the downloadable install-helper.ps1 rendered
here) polls OUTBOUND for jobs with a dedicated service-account API key. When
an ADMIN clicks "Set up Hermes now", a job row is queued; the helper claims
it, runs its single hardcoded install/start-Hermes routine, and reports
progress lines back for the Tasks-page banner.

Security posture (deliberate, keep it this way):
  * The gateway never sends code to the host. A claimed job carries only
    lifecycle state + Hermes's two config FILES (data, not script) rendered
    from hermes_setup's shared templates. The helper's behavior is fixed at
    helper-install time.
  * The helper authenticates as its own least-privilege service account
    (hermes-helper@service.local, role L1); the claim/report endpoints reject
    every other principal, including the n8n bot's key.
  * helper_online() is in-memory (resets on backend restart) — worst case the
    banner shows "helper offline" for one poll cycle after a restart.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from fastapi import HTTPException
from sqlalchemy import select, update as sa_update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.api_key import ApiKey, generate_key
from app.models.hermes_host_job import (
    ACTIVE_HOST_JOB_STATUSES,
    HOST_JOB_KIND_SETUP,
    HermesHostJob,
)
from app.models.user import User

HELPER_EMAIL = "hermes-helper@service.local"

# Helper polls every ~5s; two missed polls ≈ offline.
_HELPER_ONLINE_WINDOW_S = 15.0
_helper_last_seen: datetime | None = None

# Reported log lines are operational one-liners; cap the column against a
# misbehaving helper. Oldest lines are dropped first (tail kept).
_LOG_CAP_CHARS = 64_000

_TERMINAL_STATUSES = frozenset({"succeeded", "failed"})
_REPORTABLE_STATUSES = frozenset({"running"}) | _TERMINAL_STATUSES

_HELPER_SCRIPT_TEMPLATE = r"""# install-helper.ps1 -- generated by the Company AI Gateway (Tasks page)
#
# ONE-TIME install of the Hermes host helper. After this, setting up or
# restarting Hermes is a single button on the gateway's Tasks page, and the
# helper auto-starts Hermes again after every reboot/logon.
#
# What it does (this same file is both installer and helper):
#   install mode (default): writes config to %LOCALAPPDATA%\hermes-helper\,
#     copies itself there, registers a logon Scheduled Task
#     ('HermesGatewayHelper', current user, hidden), and starts it.
#   -Run mode (used by the task): polls the gateway every 5s for setup jobs
#     and keeps Hermes running. Its ONLY action is the hardcoded
#     install/start-Hermes routine below -- the gateway can trigger it, but
#     can never send it code to execute.
#
# Run from PowerShell:
#   powershell -ExecutionPolicy Bypass -File .\install-helper.ps1
param([switch]$Run)

$ErrorActionPreference = 'Stop'
$helperDir = Join-Path $env:LOCALAPPDATA 'hermes-helper'
$configPath = Join-Path $helperDir 'config.json'
$logPath = Join-Path $helperDir 'helper.log'
$taskName = 'HermesGatewayHelper'

if (-not $Run) {
    # ---------------- install mode ----------------
    New-Item -ItemType Directory -Force $helperDir | Out-Null
    @{ gateway_url = '__GATEWAY_URL__'; api_key = '__HELPER_KEY__' } |
        ConvertTo-Json | Out-File -Encoding utf8 $configPath
    Copy-Item $PSCommandPath (Join-Path $helperDir 'helper.ps1') -Force

    $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument (
        '-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "{0}" -Run' -f (Join-Path $helperDir 'helper.ps1'))
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    try { Stop-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue } catch {}
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Force | Out-Null
    Start-ScheduledTask -TaskName $taskName
    Write-Host "Helper installed to $helperDir and started (Scheduled Task '$taskName', runs at logon)."
    Write-Host 'You can close this window - everything else happens from the gateway web page.'
    exit 0
}

# ---------------- run mode: the polling loop ----------------
$cfg = Get-Content $configPath -Raw | ConvertFrom-Json
$gw = $cfg.gateway_url.TrimEnd('/')
$headers = @{ 'X-API-Key' = $cfg.api_key }

function Write-Log($msg) {
    if ((Test-Path $logPath) -and ((Get-Item $logPath).Length -gt 1MB)) { Clear-Content $logPath }
    "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')  $msg" | Out-File -Append -Encoding utf8 $logPath
}

function Test-HermesUp {
    try {
        $c = New-Object Net.Sockets.TcpClient
        $ok = $c.ConnectAsync('127.0.0.1', 8642).Wait(1000)
        $c.Close()
        return $ok
    } catch { return $false }
}

function Start-HermesGateway {
    # Resolve 'hermes' via PATH inside a fresh shell; hidden, detached.
    Start-Process -FilePath 'powershell.exe' -WindowStyle Hidden -ArgumentList (
        '-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -Command "hermes gateway run"')
}

function Send-Report($jobId, $status, $line) {
    $body = @{}
    if ($status) { $body.status = $status }
    if ($line) { $body.log = $line }
    try {
        Invoke-RestMethod -Method Post -Uri "$gw/hermes/host-jobs/$jobId/report" `
            -Headers $headers -ContentType 'application/json' -Body ($body | ConvertTo-Json) | Out-Null
    } catch { Write-Log "report failed: $_" }
}

function Invoke-SetupJob($job) {
    # The one and only thing this helper knows how to do.
    Send-Report $job.id $null 'Helper picked up the job on the host.'

    $hermesDir = Join-Path $env:LOCALAPPDATA 'hermes'
    New-Item -ItemType Directory -Force $hermesDir | Out-Null
    $cfgY = Join-Path $hermesDir 'config.yaml'
    if (-not (Test-Path $cfgY)) {
        [IO.File]::WriteAllText($cfgY, $job.config_yaml)
        Send-Report $job.id $null 'Wrote config.yaml.'
    }
    $envF = Join-Path $hermesDir '.env'
    if (-not (Test-Path $envF)) {
        [IO.File]::WriteAllText($envF, $job.env_file)
        Send-Report $job.id $null 'Wrote .env.'
    }

    if (-not (Get-Command hermes -ErrorAction SilentlyContinue)) {
        Send-Report $job.id $null 'Installing Hermes Agent (downloads Python, Node, Git Bash - takes a few minutes)...'
        $inst = Join-Path $env:TEMP 'hermes-install.ps1'
        Invoke-RestMethod 'https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.ps1' -OutFile $inst
        & $inst -SkipSetup *>> $logPath
        $env:Path = [Environment]::GetEnvironmentVariable('Path', 'User') + ';' + [Environment]::GetEnvironmentVariable('Path', 'Machine')
        if (-not (Get-Command hermes -ErrorAction SilentlyContinue)) {
            Send-Report $job.id 'failed' 'Installer finished but the hermes CLI was not found on PATH.'
            return
        }
        Send-Report $job.id $null 'Hermes installed.'
    }

    if (-not (Test-HermesUp)) {
        Send-Report $job.id $null 'Starting hermes gateway on port 8642...'
        Start-HermesGateway
    }
    $deadline = (Get-Date).AddSeconds(120)
    while ((Get-Date) -lt $deadline) {
        if (Test-HermesUp) {
            Send-Report $job.id 'succeeded' 'Hermes API server is up on port 8642.'
            return
        }
        Start-Sleep -Seconds 2
    }
    Send-Report $job.id 'failed' 'Timed out waiting for port 8642 to come up (see helper.log on the host).'
}

Write-Log 'helper started'
while ($true) {
    # Keep Hermes alive across reboots/crashes: if it's installed and
    # configured but not listening, start it.
    try {
        if ((Get-Command hermes -ErrorAction SilentlyContinue) -and
            (Test-Path (Join-Path $env:LOCALAPPDATA 'hermes\.env')) -and
            -not (Test-HermesUp)) {
            Write-Log 'hermes not listening - starting it'
            Start-HermesGateway
        }
    } catch { Write-Log "autostart error: $_" }

    try {
        $resp = Invoke-WebRequest -UseBasicParsing -Uri "$gw/hermes/host-jobs/pending" -Headers $headers -TimeoutSec 10
        if ($resp.StatusCode -eq 200 -and $resp.Content) {
            $job = $resp.Content | ConvertFrom-Json
            Write-Log ("claimed job " + $job.id)
            try { Invoke-SetupJob $job }
            catch {
                Send-Report $job.id 'failed' ("Helper error: " + $_.Exception.Message)
                Write-Log "setup error: $_"
            }
        }
    } catch { Write-Log "poll failed: $_" }

    Start-Sleep -Seconds 5
}
"""


# ---------------------------------------------------------------------------
# Helper liveness (in-memory)
# ---------------------------------------------------------------------------

def mark_helper_seen() -> None:
    global _helper_last_seen
    _helper_last_seen = datetime.now(timezone.utc)


def helper_online() -> bool:
    if _helper_last_seen is None:
        return False
    return (datetime.now(timezone.utc) - _helper_last_seen).total_seconds() < _HELPER_ONLINE_WINDOW_S


# ---------------------------------------------------------------------------
# Job lifecycle
# ---------------------------------------------------------------------------

async def create_job(session: AsyncSession, admin: User) -> HermesHostJob:
    active = (
        await session.execute(
            select(HermesHostJob)
            .where(HermesHostJob.status.in_(ACTIVE_HOST_JOB_STATUSES))
            .limit(1)
        )
    ).scalar_one_or_none()
    if active is not None:
        raise HTTPException(status_code=409, detail="A Hermes setup job is already in progress")

    job = HermesHostJob(kind=HOST_JOB_KIND_SETUP, status="queued", created_by=admin.id)
    session.add(job)
    await session.commit()
    return job


async def claim_pending(session: AsyncSession) -> HermesHostJob | None:
    """Atomically hand the oldest queued job to the helper (queued → running).

    Every call — including empty ones — counts as a helper heartbeat.
    """
    mark_helper_seen()
    job = (
        await session.execute(
            select(HermesHostJob)
            .where(HermesHostJob.status == "queued")
            .order_by(HermesHostJob.created_at)
            .limit(1)
            .with_for_update(skip_locked=True)
        )
    ).scalar_one_or_none()
    if job is None:
        return None
    job.status = "running"
    job.claimed_at = datetime.now(timezone.utc)
    await session.commit()
    # updated_at is DB-generated on UPDATE (onupdate=func.now()) and expired by
    # the flush; refresh eagerly so response serialization never lazy-loads it
    # outside the async context (MissingGreenlet -> 500 after commit).
    await session.refresh(job)
    return job


async def report(
    session: AsyncSession,
    job_id: uuid.UUID,
    *,
    status: str | None,
    log: str | None,
) -> HermesHostJob:
    if status is not None and status not in _REPORTABLE_STATUSES:
        raise HTTPException(status_code=422, detail=f"status must be one of {sorted(_REPORTABLE_STATUSES)}")

    job = (
        await session.execute(select(HermesHostJob).where(HermesHostJob.id == job_id))
    ).scalar_one_or_none()
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")
    if job.status in _TERMINAL_STATUSES:
        raise HTTPException(status_code=409, detail="Job already finished")

    if log:
        combined = (job.log_text + "\n" if job.log_text else "") + log.strip()
        job.log_text = combined[-_LOG_CAP_CHARS:]
    if status is not None:
        job.status = status
        if status in _TERMINAL_STATUSES:
            job.finished_at = datetime.now(timezone.utc)
    await session.commit()
    # Same updated_at/onupdate refresh rationale as claim_pending().
    await session.refresh(job)
    return job


async def latest(session: AsyncSession) -> HermesHostJob | None:
    return (
        await session.execute(
            select(HermesHostJob).order_by(HermesHostJob.created_at.desc()).limit(1)
        )
    ).scalar_one_or_none()


# ---------------------------------------------------------------------------
# Helper credential + installer script
# ---------------------------------------------------------------------------

async def mint_helper_key(session: AsyncSession) -> str:
    """Upsert the helper's least-privilege service account and mint a fresh
    key, revoking any previous ones (each helper-script download rotates the
    credential — only the newest installed helper keeps working)."""
    user = (
        await session.execute(select(User).where(User.google_email == HELPER_EMAIL))
    ).scalar_one_or_none()
    if user is None:
        user = User(
            google_email=HELPER_EMAIL,
            display_name="Hermes host helper",
            role="L1",
            is_active=True,
            consent_acknowledged_at=datetime.now(timezone.utc),
        )
        session.add(user)
        await session.flush()

    await session.execute(
        sa_update(ApiKey)
        .where(ApiKey.service_user_id == user.id, ApiKey.revoked_at.is_(None))
        .values(revoked_at=datetime.now(timezone.utc))
    )
    raw, key_hash = generate_key()
    session.add(ApiKey(name="hermes-helper", key_hash=key_hash, service_user_id=user.id))
    await session.commit()
    return raw


def render_helper_script(api_key: str, gateway_url: str = "http://localhost:8000") -> str:
    return (
        _HELPER_SCRIPT_TEMPLATE
        .replace("__GATEWAY_URL__", gateway_url)
        .replace("__HELPER_KEY__", api_key)
    )


# A bare .ps1 opens in an editor on double-click instead of running — this
# wraps render_helper_script()'s output in a self-extracting .cmd so the
# download is actually double-click-runnable. The header is a fixed number
# of lines; `Select-Object -Skip` (NOT `Get-Content -Skip`, which only
# exists in PowerShell 7+ — Windows ships Windows PowerShell 5.1, where
# `powershell.exe` lacks it, live-verified against 5.1.26100) peels the
# header off and writes the remainder (the PS1 payload, byte-identical to
# render_helper_script()) to a temp file, then runs that. `exit /b` on the
# last header line stops cmd.exe before it ever tries to parse the PS1
# payload as batch commands. CRLF throughout — required for cmd.exe,
# tolerated by PowerShell.
_CMD_STUB_LINES = 6
_CMD_STUB = (
    "@echo off\r\n"
    "setlocal\r\n"
    f"powershell -NoProfile -Command \"Get-Content -LiteralPath '%~f0' | Select-Object -Skip {_CMD_STUB_LINES} | "
    "Set-Content -Encoding utf8 '%TEMP%\\hermes-helper-install.ps1'\"\r\n"
    "powershell -NoProfile -ExecutionPolicy Bypass -File \"%TEMP%\\hermes-helper-install.ps1\"\r\n"
    "pause\r\n"
    "exit /b\r\n"
)
assert _CMD_STUB.count("\r\n") == _CMD_STUB_LINES, "keep _CMD_STUB_LINES in sync with _CMD_STUB"


def render_helper_installer_cmd(api_key: str, gateway_url: str = "http://localhost:8000") -> str:
    ps1 = render_helper_script(api_key, gateway_url)
    payload = ps1.replace("\r\n", "\n").replace("\n", "\r\n")
    return _CMD_STUB + payload
