"""
app/services/hermes_setup.py

Task 3.13 -- Hermes host-setup support for the Tasks page.

Hermes runs natively on the Docker host (not in this compose stack), so the
backend can't install or start it itself. What it CAN do:

  * probe() -- is Hermes's OpenAI-compatible API server reachable right now?
    Drives the online/offline banner on the Tasks page.
  * render_setup_script() -- a ready-to-run PowerShell script an ADMIN
    downloads and runs once on the host. It writes Hermes's config
    (pre-filled with this gateway's HERMES_API_KEY + Ollama endpoint,
    mirroring what the `hermes-init` compose service writes in the Docker
    fallback), runs NousResearch's official installer if needed, and starts
    `hermes gateway run`.

The rendered script embeds HERMES_API_KEY (it must become Hermes's own
API_SERVER_KEY), so the download endpoint is ADMIN-only and audit-logged.
"""
from __future__ import annotations

import httpx
from pydantic import BaseModel

from app.config import settings

# Short and non-configurable on purpose: this feeds a UI poll, and a hung
# probe should never hold the request open anywhere near llm timeouts.
_PROBE_TIMEOUT_S = 3.0

# Hermes's own config files — single source shared by the downloadable setup
# script (below) and the host-helper job payload (hermes_host_jobs.py). Both
# mirror what the hermes-init compose service writes in the Docker fallback.
_CONFIG_YAML_TEMPLATE = """\
model:
  provider: custom
  model: __OLLAMA_MODEL__
  base_url: __OLLAMA_URL__
  api_key: "none"
"""

_ENV_FILE_TEMPLATE = """\
API_SERVER_ENABLED=true
API_SERVER_HOST=0.0.0.0
API_SERVER_PORT=8642
API_SERVER_KEY=__API_KEY__
"""


def render_config_yaml() -> str:
    return (
        _CONFIG_YAML_TEMPLATE
        .replace("__OLLAMA_URL__", settings.hermes_ollama_url)
        .replace("__OLLAMA_MODEL__", settings.hermes_ollama_model)
    )


def render_env_file() -> str:
    return _ENV_FILE_TEMPLATE.replace("__API_KEY__", settings.hermes_api_key)

_SETUP_SCRIPT_TEMPLATE = r"""# install-hermes.ps1 -- generated by the Company AI Gateway (Tasks page)
#
# Installs NousResearch's Hermes Agent natively on this machine and starts its
# OpenAI-compatible API server on port 8642, pre-configured so the gateway's
# backend-api container can reach it at http://host.docker.internal:8642/v1.
#
# Run it from PowerShell:
#   powershell -ExecutionPolicy Bypass -File .\install-hermes.ps1
# (Double-clicking a .ps1 opens an editor on most Windows setups -- run it
# from a terminal instead.)
$ErrorActionPreference = 'Stop'

$hermesDir = Join-Path $env:LOCALAPPDATA 'hermes'
New-Item -ItemType Directory -Force $hermesDir | Out-Null

# 1) Config -- written only if absent, so an existing install's live
#    sessions/memory/skills are never clobbered (same never-overwrite rule as
#    the hermes-init service in the Docker fallback).
$configPath = Join-Path $hermesDir 'config.yaml'
if (-not (Test-Path $configPath)) {
@'
__CONFIG_YAML__
'@ | Out-File -Encoding utf8 $configPath
Write-Host "wrote $configPath"
}

$envPath = Join-Path $hermesDir '.env'
if (-not (Test-Path $envPath)) {
@'
__ENV_FILE__
'@ | Out-File -Encoding utf8 $envPath
Write-Host "wrote $envPath"
}

# 2) Install Hermes if the CLI isn't on PATH yet (official installer; no
#    admin rights needed -- everything lands under %LOCALAPPDATA%\hermes).
if (-not (Get-Command hermes -ErrorAction SilentlyContinue)) {
    Write-Host 'Installing Hermes Agent (downloads Python, Node, Git Bash -- takes a few minutes)...'
    $installer = Join-Path $env:TEMP 'hermes-install.ps1'
    Invoke-RestMethod 'https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.ps1' -OutFile $installer
    & $installer -SkipSetup
    # Pick up the PATH the installer just wrote without opening a new terminal
    $env:Path = [Environment]::GetEnvironmentVariable('Path', 'User') + ';' + [Environment]::GetEnvironmentVariable('Path', 'Machine')
}

# 3) Start the API server. Keep this window open; after a reboot just run
#    `hermes gateway run` again (config persists in %LOCALAPPDATA%\hermes).
Write-Host 'Starting Hermes gateway on port 8642...'
hermes gateway run
"""


class HermesStatus(BaseModel):
    """Reachability snapshot for the Tasks-page banner."""
    configured: bool   # HERMES_API_KEY set -> the model is registered at all
    reachable: bool    # GET {HERMES_API_URL}/models answered 200 just now


async def probe() -> HermesStatus:
    """One live reachability check against Hermes's /models endpoint."""
    if not settings.hermes_api_key:
        return HermesStatus(configured=False, reachable=False)

    url = settings.hermes_api_url.rstrip("/") + "/models"
    try:
        async with httpx.AsyncClient(timeout=_PROBE_TIMEOUT_S) as client:
            resp = await client.get(
                url, headers={"Authorization": f"Bearer {settings.hermes_api_key}"}
            )
        return HermesStatus(configured=True, reachable=resp.status_code == 200)
    except httpx.HTTPError:
        return HermesStatus(configured=True, reachable=False)


def render_setup_script() -> str:
    """Fill the PowerShell template with this deployment's live settings.

    Plain .replace() rather than str.format(): the template is full of
    PowerShell ${}/{} blocks that format() would choke on.
    """
    return (
        _SETUP_SCRIPT_TEMPLATE
        .replace("__CONFIG_YAML__", render_config_yaml().rstrip("\n"))
        .replace("__ENV_FILE__", render_env_file().rstrip("\n"))
    )
